project:
  type: website

website:
  title: "Handmade Algorithms"
  navbar:
    left:
      - text: Code
        href: main.ipynb

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



